### ISSUE TITLE
CS is low during 80 clock ticks init

### ISSUE THREAD

**Issue by Iangitpers** [elehobica/pico_fatfs_test#2]
In tf_card.c in disk_initialize around line 285 CS is taken LOW before sending the 80 dummy clocks. Everything I've read says CS should be high during init. I commented out CS_LOW().

**Comment by elehobica** [comment]
@Iangitpers Thank you for your remark. I deleted CS_LOW() since it seems quite right from several information I've checked.
```
	FCLK_SLOW();
	for (n = 10; n; n--) xchg_spi(0xFF);	/* Send 80 dummy clocks */
```
